-- TEMPORARY TABLE ARE ONLY AVAILABLE FOR TEMPORARY SESSION AND ONCE YOU EXIT SQL AND RE-ENTER SQL YOU WON'T SEE THEM-- 
-- THEY ARE MOSTLY USE FOR CHECK THE DATA TEMPORARILY & FOR MANUPULATING DATA FOR CHECKING IN MYSQL; NOT FOR PERMANENT USE CASE -- 
-- IT LIVES IN MEMORY OF OUR COMPUTER OR MACHINE NOT STORED IN HARDDRIVE --
    

CREATE TEMPORARY TABLE temp_table4
( first_name VARCHAR (50), 
  last_name VARCHAR (50),
  home_address VARCHAR (100) 
);

INSERT INTO temp_table4 (First_Name, Last_Name, Home_Address) 
VALUES ('Adnan', 'Shafiq', 'House No A-15, Military Society, New Bronzewick, California'); 

SELECT * 
FROM temp_table4; 

-- CREATING TEMPORARY TABLE WITH IN THE EXISTING TABLE -- 

CREATE TEMPORARY TABLE  SALARY_OVER_60K 
SELECT * 
FROM employee_salary
WHERE salary >= 60000
;

SELECT * 
FROM SALARY_OVER_60K
