-- EVENTS -- IT JUST LIKE A TRIGGER BUT IT IS EXECUTED ON SCHEDULE UNLIKE AN TRIGGER WHICH HAPPENS WHEN A EVENT TAKE PLACE -- 
-- WHEN YOU ARE IMPORTING DATA OR EXPORTING DATA TO SPECIFIC FILE PATH YOU USE AN EVENT TO DO THE TASK AUTOMATICALLY AS PER THE SCHEDULE --

-- CREATE AN EVENT FOR THOSE PEOPLE WHO WILL BE 50 EVERY DAY OR ON A SCHEDULE AND THIS WILL BE DELETED FROM THE TABLE AND THEY WILL RETIRED -- 
 
    
SELECT * 
FROM employee_demographics ;


DELIMITER $$ 
CREATE EVENT Remove_Retire_Person 
ON SCHEDULE EVERY 30 SECOND 
DO
BEGIN 
	DELETE  
    FROM employee_demographics
    WHERE age >= 50; 
END $$ 
DELIMITER ;

SHOW VARIABLES LIKE 'event';
